
# OpenAI/代理/网关 配置（中文内容，文件名英文，按你的偏好）
openai:
  base_url: "https://your-gateway.example.com"   # 现网关地址（可替换），支持反向代理到 OpenAI
  api_key: "YOUR_API_KEY"                        # 在应用内加密存储
  model: "gpt-4.1-mini"                          # 可在设置中改为 gpt-4.1, o4-mini 等

proxy:                                           # 默认不开启
  type: "NONE"                                   # NONE | HTTP | HTTPS | SOCKS5
  host: ""
  port: 0
  auth_user: ""
  auth_pass: ""

gateway:
  # 网关的Basic认证（如果需要），格式为 base64(user:pass)；也可置空，应用会基于用户名/密码生成
  basic: ""
